a=input("Receiver:")
b=input("Sender:")
print("############################")
print(a)
print()
print("Happy New Year to you.")
print()
print("           yours",b)
print("############################")